@host = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAxMTY2MDI5fQ.bXIYbnM2g07oCAXsZDECDfPq3uOH7ZW1d055pZR4wtc

###
# LOGIN
POST http://localhost:3000/login
content-type: application/json

{    
    "email": "hartung.will@gmail.com",
    "senha": "babalu2020"
}

###
###

###
# LISTA
GET {{host}}/atendimentos
Authorization: {{token}}
###


###
# LISTA UM
GET {{host}}/atendimentos/4
Authorization: {{token}}
###

###
# INSERE
POST {{host}}/atendimentos HTTP/1.1
Authorization: {{token}}
content-type: application/json

{    
    "cliente": "Cara Estranho", 
    "pet": "Laika",
    "servico": "tosa",
    "status": "recusado",
    "observacoes": "o cachorro é puro ranço"
}

###

###
# ATUALIZA
PATCH {{host}}/atendimentos/5
Authorization: {{token}}
content-type: application/json

{
    "id": 5,     
    "cliente": "Gilmar",
    "pet": "Roberval",
    "servico": "banho",
    "status": "recusado 2x",
    "observacoes": "ladrão de chocolates"
}

###

###
# DELETE
DELETE {{host}}/atendimentos/6 HTTP/1.1
Authorization: {{token}}
###
