# VARIÁVEIS
@host = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAwMzkwOTA3fQ.H5EUbBFXESgblkMZv5V358yrqaPAYvPVkM9o2svGOJE

###
# LOGIN
POST {{host}}/login
content-type: application/json

{    
    "email": "william.hartung@mira.eti.br",
    "senha": "babalu2020"
}

###

# LISTA
GET {{host}}/usuarios
# Authorization: {{token}}

###
# INSERE
POST {{host}}/usuarios HTTP/1.1
content-type: application/json

{    
    "nome": "Damaris Mariano", 
    "email": "damaris@portadosolturismo.com.br",
    "senha": "admin"    
}

###

# ALTERA
PATCH {{host}}/usuarios/1 
content-type: application/json

{
    "nome": "William Hartung", 
    "email": "william.hartung@mira.eti.br",
    "senha": "babalu2020"    
}

###

# DELETE
DELETE {{host}}/usuarios/4 HTTP/1.1
Authorization: {{token}}