# VARIÁVEIS
@host = http://localhost:3000
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjAxMTY2MDI5fQ.bXIYbnM2g07oCAXsZDECDfPq3uOH7ZW1d055pZR4wtc

###
# LOGIN
POST http://localhost:3000/login
content-type: application/json

{    
    "email": "hartung.will@gmail.com.br",
    "senha": "babalu2020"
}

###
###

###
# LISTA
GET {{host}}/usuarios
Authorization: {{token}}
# Authorization: {{token}}

###
###

###
# INSERE
POST {{host}}/usuarios HTTP/1.1
Authorization: {{token}}
content-type: application/json

{    
    "nome": "William Hartung 3", 
    "email": "hartung.weebs@gmail.com",
    "senha": "123456"    
}

###
###

###
# ALTERA
PATCH {{host}}/usuarios/9
Authorization: {{token}}
content-type: application/json

{
    "nome": "ERROR", 
    "email": "err.weebz2@mira.eti.br",
    "senha": "babalu2020"    
}

###
###

###
# DELETE
DELETE {{host}}/usuarios/9 HTTP/1.1
Authorization: {{token}}
###
