#Tipo 1
http://localhost:3000/atendimentos

###

#Tipo 2
POST http://localhost:3000/atendimentos HTTP/1.1
content-type: application/json

{
    "id": 2, 
    "cliente": "Yu Narukami", 
    "pet": "Morgana",
    "servico": "tosa",
    "status": "agendado",
    "observacoes": "é um personagem de Persona 5"
}

